define({
	//simulation speed
	FRAME_RATE: 60,

	//game vars
	FLOOR_Y: 485,
	LEFT_WALL_X: 25,
	RIGHT_WALL_X: 775,

	//network
	CLIENT_OUTGOING_MESSAGE_BUFFER_TIME: 3 / 60,
	SERVER_OUTGOING_MESSAGE_BUFFER_TIME: 3 / 60
});