define({
	//simulation speed
	FRAME_RATE: 60,

	//game
	LEFT_BOUND: 50,
	RIGHT_BOUND: 750,
	BOTTOM_BOUND: 475,

	//network
	CLIENT_OUTGOING_MESSAGE_BUFFER_TIME: 3 / 60,
	SERVER_OUTGOING_MESSAGE_BUFFER_TIME: 3 / 60
});